//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeDsmServiceTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MakeDsmServiceTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;functions.h&quot;
        ///
        ///int factorial(int n){
        ///    if(n!=1){
        ///	return(n * factorial(n-1));
        ///    }
        ///    else return 1;
        ///}
        ///.
        /// </summary>
        internal static string factorial {
            get {
                return ResourceManager.GetString("factorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void print_hello();
        ///int factorial(int n);
        ///.
        /// </summary>
        internal static string functions {
            get {
                return ResourceManager.GetString("functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;iostream&gt;
        ///#include &quot;functions.h&quot;
        ///
        ///void print_hello(){
        ///   std::cout &lt;&lt; &quot;Hello World!&quot;;
        ///}
        ///.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all: hello
        ///
        ///hello: main.o factorial.o hello.o
        ///    g++ main.o factorial.o hello.o -o hello
        ///
        ///main.o: main.cpp
        ///    g++ -c main.cpp
        ///
        ///factorial.o: factorial.cpp
        ///    g++ -c factorial.cpp
        ///
        ///hello.o: hello.cpp
        ///    g++ -c hello.cpp
        ///
        ///clean:
        ///    del *o hello.
        /// </summary>
        internal static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;iostream&gt;
        ///#include &quot;functions.h&quot;
        ///
        ///int main(){
        ///    print_hello();
        ///    //std::cout &lt;&lt; std::endl;
        ///    std::cout &lt;&lt; &quot;The factorial of 5 is &quot; &lt;&lt; factorial(5) ;//&lt;&lt; endl;
        ///    return 0;
        ///}
        ///.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
    }
}
